version: "3.9"
services: 
  app:
    build: ./app
    environment: 
      - TOKEN=token
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=userDB
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
  postgres:
    build: ./database
    environment: 
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=userDB
      - PGDATA=/dataFiles
    volumes:
      - ./database/dataFiles:/dataFiles
    # ports:
    #   - '5432:5432'
